interface Word {
    text: string;
    translations: string[];
}


export const englishWords: Word[] = [
    { text: "time", translations: ["tiempo", "temps"] },
    { text: "person", translations: ["persona", "personne"] },
    { text: "year", translations: ["año", "année"] },
    { text: "way", translations: ["camino", "chemin"] },
    { text: "day", translations: ["día", "jour"] },
    { text: "thing", translations: ["cosa", "chose"] },
    { text: "world", translations: ["mundo", "monde"] },
    { text: "life", translations: ["vida", "vie"] },
    { text: "hand", translations: ["mano", "main"] },
    { text: "part", translations: ["parte", "partie"] },
    { text: "child", translations: ["niño", "enfant"] },
    { text: "eye", translations: ["ojo", "œil"] },
    { text: "woman", translations: ["mujer", "femme"] },
    { text: "place", translations: ["lugar", "lieu"] },
    { text: "work", translations: ["trabajo", "travail"] },
    { text: "week", translations: ["semana", "semaine"] },
    { text: "case", translations: ["caso", "cas"] },
    { text: "point", translations: ["punto", "point"] },
    { text: "government", translations: ["gobierno", "gouvernement"] },
    { text: "company", translations: ["empresa", "entreprise"] },
    { text: "number", translations: ["número", "nombre"] },
    { text: "group", translations: ["grupo", "groupe"] },
    { text: "problem", translations: ["problema", "problème"] },
    { text: "fact", translations: ["hecho", "fait"] },
    { text: "water", translations: ["agua", "eau"] },
    { text: "good", translations: ["bueno", "bon"] },
    { text: "new", translations: ["nuevo", "nouveau"] },
    { text: "first", translations: ["primero", "premier"] },
    { text: "last", translations: ["último", "dernier"] },
    { text: "long", translations: ["largo", "long"] },
    { text: "great", translations: ["gran", "grand"] },
    { text: "little", translations: ["pequeño", "petit"] },
    { text: "own", translations: ["propio", "propre"] },
    { text: "other", translations: ["otro", "autre"] },
    { text: "old", translations: ["viejo", "vieux"] },
    { text: "right", translations: ["correcto", "droit"] },
    { text: "big", translations: ["grande", "grand"] },
    { text: "high", translations: ["alto", "haut"] },
    { text: "different", translations: ["diferente", "différent"] },
    { text: "small", translations: ["pequeño", "petit"] },
    { text: "large", translations: ["grande", "large"] },
    { text: "next", translations: ["siguiente", "prochain"] },
    { text: "early", translations: ["temprano", "tôt"] },
    { text: "young", translations: ["joven", "jeune"] },
    { text: "important", translations: ["importante", "important"] },
    { text: "few", translations: ["pocos", "peu"] },
    { text: "public", translations: ["público", "public"] },
    { text: "bad", translations: ["malo", "mauvais"] },
    { text: "same", translations: ["mismo", "même"] },
    { text: "able", translations: ["capaz", "capable"] },
    { text: "be", translations: ["ser", "être"] },
    { text: "have", translations: ["tener", "avoir"] },
    { text: "do", translations: ["hacer", "faire"] },
    { text: "say", translations: ["decir", "dire"] },
    { text: "get", translations: ["obtener", "obtenir"] },
    { text: "make", translations: ["hacer", "fabriquer"] },
    { text: "go", translations: ["ir", "aller"] },
    { text: "know", translations: ["saber", "savoir"] },
    { text: "take", translations: ["tomar", "prendre"] },
    { text: "see", translations: ["ver", "voir"] },
    { text: "come", translations: ["venir", "venir"] },
    { text: "think", translations: ["pensar", "penser"] },
    { text: "look", translations: ["mirar", "regarder"] },
    { text: "want", translations: ["querer", "vouloir"] },
    { text: "give", translations: ["dar", "donner"] },
    { text: "use", translations: ["usar", "utiliser"] },
    { text: "find", translations: ["encontrar", "trouver"] },
    { text: "tell", translations: ["contar", "raconter"] },
    { text: "ask", translations: ["preguntar", "demander"] },
    { text: "seem", translations: ["parecer", "sembler"] },
    { text: "feel", translations: ["sentir", "ressentir"] },
    { text: "try", translations: ["intentar", "essayer"] },
    { text: "leave", translations: ["dejar", "laisser"] },
    { text: "call", translations: ["llamar", "appeler"] },

    // Everyday Objects & Concepts
    { text: "book", translations: ["libro", "livre"] },
    { text: "house", translations: ["casa", "maison"] },
    { text: "door", translations: ["puerta", "porte"] },
    { text: "window", translations: ["ventana", "fenêtre"] },
    { text: "table", translations: ["mesa", "table"] },
    { text: "chair", translations: ["silla", "chaise"] },
    { text: "bed", translations: ["cama", "lit"] },
    { text: "room", translations: ["habitación", "chambre"] },
    { text: "car", translations: ["coche", "voiture"] },
    { text: "street", translations: ["calle", "rue"] },
    { text: "city", translations: ["ciudad", "ville"] },
    { text: "food", translations: ["comida", "nourriture"] },
    { text: "money", translations: ["dinero", "argent"] },
    { text: "paper", translations: ["papel", "papier"] },
    { text: "pen", translations: ["bolígrafo", "stylo"] },
    { text: "friend", translations: ["amigo", "ami"] },
    { text: "family", translations: ["familia", "famille"] },
    { text: "mother", translations: ["madre", "mère"] },
    { text: "father", translations: ["padre", "père"] },
    { text: "brother", translations: ["hermano", "frère"] },
    { text: "sister", translations: ["hermana", "sœur"] },

    // Nature & Environment
    { text: "tree", translations: ["árbol", "arbre"] },
    { text: "flower", translations: ["flor", "fleur"] },
    { text: "grass", translations: ["hierba", "herbe"] },
    { text: "sun", translations: ["sol", "soleil"] },
    { text: "moon", translations: ["luna", "lune"] },
    { text: "star", translations: ["estrella", "étoile"] },
    { text: "sky", translations: ["cielo", "ciel"] },
    { text: "cloud", translations: ["nube", "nuage"] },
    { text: "rain", translations: ["lluvia", "pluie"] },
    { text: "snow", translations: ["nieve", "neige"] },
    { text: "fire", translations: ["fuego", "feu"] },
    { text: "river", translations: ["río", "rivière"] },
    { text: "sea", translations: ["mar", "mer"] },
    { text: "mountain", translations: ["montaña", "montagne"] },
    { text: "animal", translations: ["animal", "animal"] },
    { text: "dog", translations: ["perro", "chien"] },
    { text: "cat", translations: ["gato", "chat"] },
    { text: "bird", translations: ["pájaro", "oiseau"] },
    { text: "fish", translations: ["pez", "poisson"] },

    // Descriptive Adjectives
    { text: "happy", translations: ["feliz", "heureux"] },
    { text: "sad", translations: ["triste", "triste"] },
    { text: "fast", translations: ["rápido", "rapide"] },
    { text: "slow", translations: ["lento", "lent"] },
    { text: "hot", translations: ["caliente", "chaud"] },
    { text: "cold", translations: ["frío", "froid"] },
    { text: "strong", translations: ["fuerte", "fort"] },
    { text: "weak", translations: ["débil", "faible"] },
    { text: "beautiful", translations: ["hermoso", "beau"] },
    { text: "ugly", translations: ["feo", "laid"] },
    { text: "clean", translations: ["limpio", "propre"] },
    { text: "dirty", translations: ["sucio", "sale"] }
];


const wordSet = new Set(englishWords.map(w => w.text));
export function isEnglishWord(word: string) {
    return wordSet.has(word)
}